# Generated by Django 3.1.3 on 2020-11-08 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Miner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minername', models.CharField(max_length=100, verbose_name='Name')),
                ('repoamount', models.IntegerField(verbose_name='Repo amount')),
                ('minedamount', models.IntegerField(verbose_name='Mined Repo Amount')),
                ('minerstatus', models.CharField(max_length=100, verbose_name='Status')),
                ('minertaskid', models.CharField(max_length=100, verbose_name='Task id')),
                ('tokenassociated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Miner.token')),
            ],
        ),
    ]
