# Generated by Django 3.1.3 on 2020-11-08 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Miner', '0002_miner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repositories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponame', models.CharField(max_length=100, verbose_name='Name')),
                ('activitystatus', models.CharField(max_length=100, verbose_name='Status')),
                ('currentminingissue', models.IntegerField(verbose_name='Current mining issue')),
                ('lastissuenumber', models.IntegerField(verbose_name='Final issue')),
                ('firstissuenumber', models.IntegerField(verbose_name='First issue')),
                ('associatedMiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Miner.miner')),
            ],
        ),
    ]
