# Generated by Django 3.1.3 on 2020-11-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miner', '0003_repositories'),
    ]

    operations = [
        migrations.AddField(
            model_name='miner',
            name='repo_list',
            field=models.TextField(default=1, verbose_name='Repositories list'),
            preserve_default=False,
        ),
    ]
