# Generated by Django 3.1.3 on 2020-11-22 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Miner', '0006_repositories_associatedstatisticworker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositories',
            name='associatedMiner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Miner.miner'),
        ),
        migrations.AlterField(
            model_name='repositories',
            name='associatedStatisticWorker',
            field=models.CharField(max_length=10000, null=True, verbose_name='Task id'),
        ),
        migrations.AlterField(
            model_name='repositories',
            name='currentminingissue',
            field=models.IntegerField(null=True, verbose_name='Current mining issue'),
        ),
        migrations.AlterField(
            model_name='repositories',
            name='firstissuenumber',
            field=models.IntegerField(null=True, verbose_name='First issue'),
        ),
        migrations.AlterField(
            model_name='repositories',
            name='lastissuenumber',
            field=models.IntegerField(null=True, verbose_name='Final issue'),
        ),
    ]
