# Generated by Django 3.1.3 on 2020-11-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miner', '0007_auto_20201122_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositories',
            name='associatedMiner',
            field=models.CharField(default=1, max_length=10000, verbose_name='Miner name'),
            preserve_default=False,
        ),
    ]
