# Generated by Django 3.1.3 on 2020-11-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miner', '0008_auto_20201122_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miner',
            name='minername',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
