# Generated by Django 3.1.3 on 2020-11-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miner', '0009_auto_20201122_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositories',
            name='reponame',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='token',
            name='tokenname',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
