# Generated by Django 3.1.3 on 2020-11-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miner', '0011_auto_20201122_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(verbose_name='Like')),
                ('heart', models.IntegerField(verbose_name='Heart')),
                ('hooray', models.IntegerField(verbose_name='Horray')),
                ('confused', models.IntegerField(verbose_name='Confused')),
                ('deslike', models.IntegerField(verbose_name='Deslike')),
                ('laught', models.IntegerField(verbose_name='Laught')),
                ('rocket', models.IntegerField(verbose_name='Rocket')),
                ('eyes', models.IntegerField(verbose_name='Eyes')),
                ('reponame', models.CharField(max_length=10000, verbose_name='Repo name')),
            ],
        ),
    ]
