# Generated by Django 3.1.3 on 2020-11-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miner', '0012_reactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='miner',
            name='statisticstaskid',
            field=models.CharField(default=1, max_length=100, verbose_name='Task id'),
            preserve_default=False,
        ),
    ]
