# Generated by Django 3.1.3 on 2020-11-22 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Miner', '0013_miner_statisticstaskid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='associatedRepo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Miner.repositories'),
        ),
        migrations.AlterField(
            model_name='issueperyear',
            name='associatedRepo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Miner.repositories'),
        ),
        migrations.AlterField(
            model_name='label',
            name='associatedRepo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Miner.repositories'),
        ),
    ]
