# Generated by Django 3.1.3 on 2020-11-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miner', '0015_auto_20201122_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositories',
            name='reponame',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
